name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Create environment files
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      run: |
        mkdir -p src/environments

        # Debug: Check if token is available
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "Error: GITHUB_TOKEN is empty!"
          exit 1
        fi

        # Validate token format
        if [[ ! "$GITHUB_TOKEN" =~ ^ghp_[a-zA-Z0-9]{36}$ ]]; then
          echo "Error: GITHUB_TOKEN format is invalid!"
          exit 1
        fi

        # Create development environment file
        cat > src/environments/environment.ts << EOL
        export const environment = {
          production: false,
          githubToken: '${GITHUB_TOKEN}',
          environment: 'development'
        };
        EOL

        # Create production environment file
        cat > src/environments/environment.prod.ts << EOL
        export const environment = {
          production: true,
          githubToken: '${GITHUB_TOKEN}',
          environment: 'production'
        };
        EOL

        # Debug: Check if token is being injected (without showing the actual token)
        echo "Token length: ${#GITHUB_TOKEN}"
        echo "Token format check: ${GITHUB_TOKEN:0:4}..."
        # Debug: Check if environment files are created
        ls -la src/environments/
        # Debug: Check environment file content (without showing the token)
        grep -v "githubToken" src/environments/environment.ts
        grep -v "githubToken" src/environments/environment.prod.ts

    - name: Build
      run: |
        # Debug: Check if environment files exist before build
        ls -la src/environments/
        # Run the build
        npm run build
        # Debug: Check if environment files are included in the build
        find dist -type f -name "*.js" -exec grep -l "githubToken" {} \;
        # Debug: List build output directory
        ls -la dist/my-insta/

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/my-insta/browser
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}

    # Add deployment steps here based on your hosting platform
