name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Create environment files
      run: |
        mkdir -p src/environments
        echo "export const environment = {
          production: false,
          githubToken: '${{ secrets.GITHUB_TOKEN }}',
          environment: 'development'
        };" > src/environments/environment.ts
        echo "export const environment = {
          production: true,
          githubToken: '${{ secrets.GITHUB_TOKEN }}',
          environment: 'production'
        };" > src/environments/environment.prod.ts

    - name: Build
      run: npm run build

    # Add deployment steps here based on your hosting platform
