name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Create environment files
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      run: |
        mkdir -p src/environments

        # Create development environment file
        cat > src/environments/environment.ts << EOL
        export const environment = {
          production: false,
          githubToken: '${GITHUB_TOKEN}',
          environment: 'development'
        };
        EOL

        # Create production environment file
        cat > src/environments/environment.prod.ts << EOL
        export const environment = {
          production: true,
          githubToken: '${GITHUB_TOKEN}',
          environment: 'production'
        };
        EOL

        # Debug: Check if token is being injected (without showing the actual token)
        echo "Token length: ${#GITHUB_TOKEN}"
        # Debug: Check if environment files are created
        ls -la src/environments/
        # Debug: Check environment file content (without showing the token)
        grep -v "githubToken" src/environments/environment.ts
        grep -v "githubToken" src/environments/environment.prod.ts

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/my-insta/browser
        branch: gh-pages

    # Add deployment steps here based on your hosting platform
