name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Setup environment files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Debug: Check token
        echo "=== Token Debug Info ==="
        echo "Token length: ${#GITHUB_TOKEN}"
        echo "Token prefix: ${GITHUB_TOKEN:0:4}"
        echo "Token exists: $([ ! -z "$GITHUB_TOKEN" ] && echo "Yes" || echo "No")"

        # Create environments directory if it doesn't exist
        mkdir -p src/environments

        # Create development environment file with properly escaped token
        cat > src/environments/environment.ts << EOF
export const environment = {
  production: false,
  githubToken: "${GITHUB_TOKEN}",
  environment: 'development'
};
EOF

        # Create production environment file with properly escaped token
        cat > src/environments/environment.prod.ts << EOF
export const environment = {
  production: true,
  githubToken: "${GITHUB_TOKEN}",
  environment: 'production'
};
EOF

        # Debug: Check environment files
        echo "=== Environment Files ==="
        ls -la src/environments/
        echo "=== Environment File Contents (without token) ==="
        grep -v "githubToken" src/environments/environment.ts
        grep -v "githubToken" src/environments/environment.prod.ts

        # Debug: Check token in files
        echo "=== Token in Files ==="
        echo "Development file token length: $(grep -o 'githubToken: "[^"]*"' src/environments/environment.ts | cut -d'"' -f2 | wc -c)"
        echo "Production file token length: $(grep -o 'githubToken: "[^"]*"' src/environments/environment.prod.ts | cut -d'"' -f2 | wc -c)"
        echo "Development file token prefix: $(grep -o 'githubToken: "[^"]*"' src/environments/environment.ts | cut -d'"' -f2 | cut -c1-4)"
        echo "Production file token prefix: $(grep -o 'githubToken: "[^"]*"' src/environments/environment.prod.ts | cut -d'"' -f2 | cut -c1-4)"

    - name: Build
      run: |
        # Debug: Check if environment files exist before build
        echo "=== Environment Files Before Build ==="
        ls -la src/environments/

        # Run the build with production configuration
        npm run build -- --configuration=production

        # Debug: List build output directory structure
        echo "=== Build Output Structure ==="
        find dist -type f

        # Verify no tokens in build output
        echo "=== Checking for exposed tokens ==="
        grep -r "ghp_" dist/ || true

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/my-insta/browser
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: true
